//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class area_city_state_view
{
    public int area_id { get; set; }
    public string area_name { get; set; }
    public Nullable<int> city_id { get; set; }
    public Nullable<int> state_id { get; set; }
    public string city_name { get; set; }
    public string state_name { get; set; }
}

public partial class area_master
{
    public int area_id { get; set; }
    public string area_name { get; set; }
    public Nullable<int> city_id { get; set; }
    public Nullable<int> state_id { get; set; }
    public string status { get; set; }

    public virtual city_master city_master { get; set; }
    public virtual state_master state_master { get; set; }
}

public partial class city_master
{
    public city_master()
    {
        this.area_master = new HashSet<area_master>();
    }

    public int city_id { get; set; }
    public string city_name { get; set; }
    public Nullable<int> state_master_id { get; set; }
    public string status { get; set; }

    public virtual ICollection<area_master> area_master { get; set; }
    public virtual state_master state_master { get; set; }
}

public partial class city_with_state_view
{
    public int state_id { get; set; }
    public string state_name { get; set; }
    public int city_id { get; set; }
    public string city_name { get; set; }
    public Nullable<int> state_master_id { get; set; }
}

public partial class state_master
{
    public state_master()
    {
        this.area_master = new HashSet<area_master>();
        this.city_master = new HashSet<city_master>();
    }

    public int state_id { get; set; }
    public string state_name { get; set; }
    public string status { get; set; }

    public virtual ICollection<area_master> area_master { get; set; }
    public virtual ICollection<city_master> city_master { get; set; }
}

public partial class tblAdmin
{
    public int Id { get; set; }
    public string UName { get; set; }
    public string UPass { get; set; }
    public string Email { get; set; }
    public Nullable<bool> IsOnline { get; set; }
    public Nullable<System.DateTime> UpDt { get; set; }
}

public partial class vehicle_type
{
    public int type_id { get; set; }
    public string type_name { get; set; }
    public string status { get; set; }
}
