//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class elts_lorry_Entities : DbContext
{
    public elts_lorry_Entities()
        : base("name=elts_lorry_Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<area_master> area_master { get; set; }
    public DbSet<city_master> city_master { get; set; }
    public DbSet<state_master> state_master { get; set; }
    public DbSet<tblAdmin> tblAdmins { get; set; }
    public DbSet<vehicle_type> vehicle_type { get; set; }
    public DbSet<city_with_state_view> city_with_state_view { get; set; }
    public DbSet<area_city_state_view> area_city_state_view { get; set; }
    public DbSet<user_details> user_details { get; set; }
    public DbSet<user_profile> user_profile { get; set; }
    public DbSet<user_profile_with_user_details_view> user_profile_with_user_details_view { get; set; }
}
