//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class area_city_state_view
{
    public int area_id { get; set; }
    public string area_name { get; set; }
    public Nullable<int> city_id { get; set; }
    public Nullable<int> state_id { get; set; }
    public string city_name { get; set; }
    public string state_name { get; set; }
}

public partial class area_master
{
    public int area_id { get; set; }
    public string area_name { get; set; }
    public Nullable<int> city_id { get; set; }
    public Nullable<int> state_id { get; set; }
    public string status { get; set; }

    public virtual city_master city_master { get; set; }
    public virtual state_master state_master { get; set; }
}

public partial class city_master
{
    public city_master()
    {
        this.area_master = new HashSet<area_master>();
    }

    public int city_id { get; set; }
    public string city_name { get; set; }
    public Nullable<int> state_master_id { get; set; }
    public string status { get; set; }

    public virtual ICollection<area_master> area_master { get; set; }
    public virtual state_master state_master { get; set; }
}

public partial class city_with_state_view
{
    public int state_id { get; set; }
    public string state_name { get; set; }
    public int city_id { get; set; }
    public string city_name { get; set; }
    public Nullable<int> state_master_id { get; set; }
}

public partial class state_master
{
    public state_master()
    {
        this.area_master = new HashSet<area_master>();
        this.city_master = new HashSet<city_master>();
        this.user_details = new HashSet<user_details>();
    }

    public int state_id { get; set; }
    public string state_name { get; set; }
    public string status { get; set; }

    public virtual ICollection<area_master> area_master { get; set; }
    public virtual ICollection<city_master> city_master { get; set; }
    public virtual ICollection<user_details> user_details { get; set; }
}

public partial class tblAdmin
{
    public int Id { get; set; }
    public string UName { get; set; }
    public string UPass { get; set; }
    public string Email { get; set; }
    public Nullable<bool> IsOnline { get; set; }
    public Nullable<System.DateTime> UpDt { get; set; }
}

public partial class user_details
{
    public user_details()
    {
        this.user_profile = new HashSet<user_profile>();
    }

    public int pro_id { get; set; }
    public string full_name { get; set; }
    public string email { get; set; }
    public string ph_no { get; set; }
    public string altr_ph_no { get; set; }
    public string address_1 { get; set; }
    public string address_2 { get; set; }
    public int city { get; set; }
    public int state { get; set; }
    public string user_type { get; set; }
    public Nullable<System.DateTime> ct_dt { get; set; }
    public Nullable<int> ct_by { get; set; }
    public Nullable<System.DateTime> up_dt { get; set; }
    public Nullable<int> up_by { get; set; }
    public string status { get; set; }

    public virtual user_details user_details1 { get; set; }
    public virtual user_details user_details2 { get; set; }
    public virtual ICollection<user_profile> user_profile { get; set; }
    public virtual state_master state_master { get; set; }
}

public partial class user_profile
{
    public int upro_id { get; set; }
    public int usr_id { get; set; }
    public string usr_name { get; set; }
    public string usr_pass { get; set; }
    public Nullable<bool> ispass_reset { get; set; }
    public Nullable<bool> isPhone_verified { get; set; }
    public Nullable<bool> isEmail_verified { get; set; }
    public Nullable<bool> isOnline { get; set; }
    public Nullable<System.DateTime> last_login { get; set; }
    public Nullable<int> failed_attempts { get; set; }
    public Nullable<System.DateTime> ct_dt { get; set; }
    public Nullable<int> ct_by { get; set; }
    public Nullable<System.DateTime> up_dt { get; set; }
    public Nullable<int> up_by { get; set; }
    public string status { get; set; }

    public virtual user_details user_details { get; set; }
}

public partial class user_profile_with_user_details_view
{
    public int pro_id { get; set; }
    public string full_name { get; set; }
    public string email { get; set; }
    public string ph_no { get; set; }
    public string address_1 { get; set; }
    public int city { get; set; }
    public string address_2 { get; set; }
    public int state { get; set; }
    public string user_type { get; set; }
    public Nullable<System.DateTime> ct_dt { get; set; }
    public Nullable<int> ct_by { get; set; }
    public Nullable<int> up_by { get; set; }
    public string status { get; set; }
    public string usr_name { get; set; }
    public string usr_pass { get; set; }
    public Nullable<bool> ispass_reset { get; set; }
    public Nullable<bool> isPhone_verified { get; set; }
    public Nullable<bool> isEmail_verified { get; set; }
    public Nullable<bool> isOnline { get; set; }
    public Nullable<System.DateTime> last_login { get; set; }
    public Nullable<int> failed_attempts { get; set; }
    public string city_name { get; set; }
    public string state_name { get; set; }
}

public partial class vehicle_type
{
    public int type_id { get; set; }
    public string type_name { get; set; }
    public string status { get; set; }
}
